# Generated by Django 4.1.1 on 2022-11-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_money',
            fields=[
                ('Accno', models.IntegerField(primary_key=True, serialize=False)),
                ('Balance', models.FloatField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
