# Generated by Django 4.1.1 on 2022-11-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_send_money'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='send_money',
            new_name='registerPage',
        ),
    ]
